---
- name: Setting up a webpage
  hosts: nobleaxis
  tasks:
  - name: Install httpd
    yum:
      name: httpd
      state: present
  
  - name: state httpd
    service:
      name: httpd
      state: started

  - name: Add index.html file
    file:
      path: /var/www/html/index.html
      state: touch
  
  - name: wirte to index.html
    copy:
      content: "<html><h1>The webpage successfully setup</h1></html>"
      dest: /var/www/html/index.html
  
  - name: Installing Firewall service
    yum:
      name: firewalld
      state: present
  
  - name: start Firewall service
    service:
      name: firewalld
      state: started
  
  - name: Add httpd service to firewall
    firewalld:
      zone: public
      permanent: yes
      service: http
      state: enabled
  
  - name: Add http port to firewall
    firewalld:
      port: 80/tcp
      permanent: yes
      state: enabled
  
  - name: Reload firewalld
    service:
      name: firewalld
      state: restarted
  
  - name: restart httpd
    service:
      name: httpd
      state: restarted
